### ISSUE TITLE
Error: C type not configured: nat

### ISSUE THREAD

**Issue by tzskp1** [akr/codegen#2]
I tried
```
 coqc ./sample/pow.v
```
But coqc says
```
Arguments _fastpow_iter (_ _ _)%nat_scope
File "./sample/pow.v", line 32, characters 0-62:
Error: C type not configured: nat
```

**Comment by akr** [comment]
I updated samples.

However, currently I changed codegen aggressively (i.e. incompatible).
coq-8.10 branch should work as the old behavior.

**Comment by tzskp1** [comment]
Thank you for your advice!
